version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/r3f-portfolio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/binance-multi-assets-singal-agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/binance-multi-assets-singal-agent/frontend"
    schedule:
      interval: "weekly"
